AWSTemplateFormatVersion: '2010-09-09'
Description: HTW Berlin - Serverless AI Pipeline (Translate + Sentiment Analysis)

Resources:
  # 1. RAW DATA BUCKET (Input Storage)
  # This bucket triggers the Lambda function when a new file is uploaded.
  RawDataBucket:
    Type: AWS::S3::Bucket
    DependsOn: LambdaInvokePermission
    Properties:
      BucketName: !Sub 'htw-raw-data-${AWS::AccountId}-${AWS::Region}'
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:*
            Function: !GetAtt AIProcessorFunction.Arn

  # 2. PROCESSED DATA BUCKET (Output Storage)
  # Stores the final JSON analysis results.
  ProcessedDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'htw-processed-data-${AWS::AccountId}-${AWS::Region}'

  # 3. IAM ROLE (Security & Permissions)
  # Grants the Lambda function permission to access S3, Comprehend, and Translate services.
  AIProcessorRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: S3AndAIAdmin
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:*
                  - comprehend:*
                  - translate:*
                  - logs:*
                Resource: '*'

  # 4. LAMBDA FUNCTION (AI Brain + Translator)
  # This function handles the logic: Read File -> Translate -> Analyze Sentiment -> Save Result.
  AIProcessorFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: HTW-Customer-Insight-AI
      Handler: index.lambda_handler
      Role: !GetAtt AIProcessorRole.Arn
      Runtime: python3.9
      Timeout: 30
      Code:
        ZipFile: |
          import json
          import boto3
          import os

          # Initialize AWS SDK clients
          s3 = boto3.client('s3')
          comprehend = boto3.client('comprehend')
          translate = boto3.client('translate') 

          def lambda_handler(event, context):
              print("AI Engine Started! Mode: Translation & Sentiment Analysis")
              
              # 1. Retrieve file information from the event trigger
              record = event['Records'][0]
              src_bucket = record['s3']['bucket']['name']
              src_key = record['s3']['object']['key']
              print(f"Processing file: {src_bucket}/{src_key}")
              
              # 2. Read the file content from the Raw Data Bucket
              try:
                  obj = s3.get_object(Bucket=src_bucket, Key=src_key)
                  original_text = obj['Body'].read().decode('utf-8')
              except Exception as e:
                  print(f"Error reading file: {str(e)}")
                  return {'status': 'error', 'message': str(e)}
              
              # 3. AMAZON TRANSLATE (Detect Language -> Translate to English)
              print("Step 1: Translating text to English...")
              try:
                  translation_response = translate.translate_text(
                      Text=original_text,
                      SourceLanguageCode='auto', # Automatically detects source language (e.g., tr, de, fr)
                      TargetLanguageCode='en'    # Translates to English
                  )
                  translated_text = translation_response['TranslatedText']
                  source_lang = translation_response['SourceLanguageCode']
                  print(f"Detected Language: {source_lang}")
              except Exception as e:
                  print(f"Translation failed: {str(e)}")
                  return {'status': 'error', 'message': 'Translation failed'}
              
              # 4. SENTIMENT ANALYSIS (Analyze the translated English text)
              print("Step 2: Analyzing sentiment...")
              sentiment_response = comprehend.detect_sentiment(Text=translated_text, LanguageCode='en')
              sentiment = sentiment_response['Sentiment']
              score = sentiment_response['SentimentScore']
              
              # 5. Prepare the final report (JSON)
              # Includes original text, detected language, translation, and sentiment scores.
              analysis_result = {
                  'original_text': original_text,
                  'detected_language': source_lang,
                  'translated_english': translated_text,
                  'sentiment_analysis': {
                      'mood': sentiment,
                      'scores': score
                  },
                  'project': 'HTW Berlin - Serverless AI Pipeline',
                  'author': 'Yigit Peker'
              }
              
              # 6. Save the result to the 'Processed' bucket
              target_bucket = src_bucket.replace('raw-data', 'processed-data')
              target_key = 'AI_RESULT_' + src_key + '.json'
              
              s3.put_object(
                  Bucket=target_bucket,
                  Key=target_key,
                  Body=json.dumps(analysis_result, indent=4)
              )
              
              print(f"Analysis successfully saved to: {target_bucket}/{target_key}")
              return {'status': 'success', 'lang': source_lang, 'mood': sentiment}

  # 5. S3 PERMISSION
  # Grants S3 permission to invoke this specific Lambda function.
  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref AIProcessorFunction
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn: !Sub 'arn:aws:s3:::htw-raw-data-${AWS::AccountId}-${AWS::Region}'
